Interface:
    orientation: "vertical"
    MDTopAppBar:
        title: "Flash Light"
        specific_text_color: app.theme_cls.bg_normal
        right_action_items: [["weather-night", lambda x: app.change_style(self)]]
        elevation: 4
    AnchorLayout:
        anchor_y:"center"
        anchor_x: "center"
        padding:0,dp(100),0,dp(100)
        MDBoxLayout:
            orientation: "vertical"
            size_hint_y:None
            height: self.minimum_height
            spacing:dp(50)
            MDLabel:
                id: timeplaceholder
                text: "00 : 00 : 00"
                font_name: "digital.ttf"
                font_size: '56sp'
                halign: "center"
                theme_text_color: "Custom"
                text_color: app.theme_cls.accent_color
                size_hint_y:None
                height: self.texture_size[1]
            MDProgressBar:
                id: progressbar
                color: app.theme_cls.primary_color
                type: "indeterminate"
                pos_hint: {"center_x":0.5}
                size_hint:None,None
                size: dp(250),dp(5)
            CustomMDAnchorLayout:
                md_bg_color: app.theme_cls.primary_color
                size_hint:None,None
                size: dp(250),dp(250)
                radius: dp(80)
                pos_hint: {"center_x":0.5}
                elevation: 4
                on_press: root.flash_on()
                anchor_y: "center"
                anchor_x: "center"
                MDIcon:
                    id: flash_icon
                    icon: "alarm-light"
                    font_size: '150sp'
                    color: app.theme_cls.bg_normal
